export const mockPropostas = [
  {
    id: "1",
    titulo: "Proposta Logística SaaS - Modelo Padrão",
    subtitulo: "Apresentação de serviços dedicados",
    tipo: "modelo",
    cliente: null,
    segmento: "Logística B2B",
    tipoServico: "Carga Fechada",
    status: "aprovada",
    favorita: true,
    guardadaNaBiblioteca: false,
    dataGuardada: null,
    totalExportacoes: 5,
    ultimaExportacaoEm: "2026-04-10T14:30:00Z",
    origemDaGuardada: null,
    criadoEm: "2026-04-01T10:00:00Z",
    atualizadoEm: "2026-04-05T14:30:00Z",
  },
  {
    id: "2",
    titulo: "Operação Dedicada - Amazon",
    subtitulo: "Distribuição Capital",
    tipo: "personalizada",
    cliente: "Amazon Logística",
    segmento: "E-commerce",
    tipoServico: "Last Mile",
    status: "enviada",
    favorita: false,
    guardadaNaBiblioteca: true,
    dataGuardada: "2026-04-09T10:00:00Z",
    totalExportacoes: 3,
    ultimaExportacaoEm: "2026-04-12T16:20:00Z",
    origemDaGuardada: "2",
    criadoEm: "2026-04-08T09:15:00Z",
    atualizadoEm: "2026-04-09T16:20:00Z",
    modeloOrigemId: "1",
  },
  {
    id: "3",
    titulo: "Proposta Spot - Indústria Química",
    subtitulo: "Transporte de Carga Perigosa",
    tipo: "personalizada",
    cliente: "Química ABC",
    segmento: "Químico",
    tipoServico: "Carga Fracionada",
    status: "rascunho",
    favorita: false,
    guardadaNaBiblioteca: false,
    dataGuardada: null,
    totalExportacoes: 0,
    ultimaExportacaoEm: null,
    origemDaGuardada: null,
    criadoEm: "2026-04-10T11:00:00Z",
    atualizarEm: "2026-04-10T11:45:00Z",
  },
  {
    id: "4",
    titulo: "Logística Reversa Varejo - Base",
    subtitulo: "Template oficial de Logística Reversa",
    tipo: "modelo",
    cliente: null,
    segmento: "Varejo",
    tipoServico: "Logística Reversa",
    status: "aprovada",
    favorita: true,
    guardadaNaBiblioteca: true,
    dataGuardada: "2026-03-20T15:00:00Z",
    totalExportacoes: 8,
    ultimaExportacaoEm: "2026-04-11T09:45:00Z",
    origemDaGuardada: "4",
    criadoEm: "2026-03-15T08:00:00Z",
    atualizadoEm: "2026-03-20T10:00:00Z",
  },
  {
    id: "5",
    titulo: "Proposta Mercado Livre - SP",
    subtitulo: "Operação Dedicada São Paulo",
    tipo: "personalizada",
    cliente: "Mercado Livre",
    segmento: "E-commerce",
    tipoServico: "Carga Fechada",
    status: "aprovada",
    favorita: false,
    guardadaNaBiblioteca: false,
    dataGuardada: null,
    totalExportacoes: 2,
    ultimaExportacaoEm: "2026-04-08T11:30:00Z",
    origemDaGuardada: null,
    criadoEm: "2026-04-05T14:00:00Z",
    atualizarEm: "2026-04-08T11:30:00Z",
  }
];