export const mockPropostas = [
  {
    id: "1",
    titulo: "Proposta Logística SaaS - Modelo Padrão",
    subtitulo: "Apresentação de serviços dedicados",
    tipo: "modelo",
    cliente: null,
    segmento: "Logística B2B",
    tipoServico: "Carga Fechada",
    status: "aprovada",
    favorita: true,
    criadoEm: "2026-04-01T10:00:00Z",
    atualizadoEm: "2026-04-05T14:30:00Z",
  },
  {
    id: "2",
    titulo: "Operação Dedicada - Amazon",
    subtitulo: "Distribuição Capital",
    tipo: "personalizada",
    cliente: "Amazon Logística",
    segmento: "E-commerce",
    tipoServico: "Last Mile",
    status: "enviada",
    favorita: false,
    criadoEm: "2026-04-08T09:15:00Z",
    atualizadoEm: "2026-04-09T16:20:00Z",
    modeloOrigemId: "1",
  },
  {
    id: "3",
    titulo: "Proposta Spot - Indústria Química",
    subtitulo: "Transporte de Carga Perigosa",
    tipo: "personalizada",
    cliente: "Química ABC",
    segmento: "Químico",
    tipoServico: "Carga Fracionada",
    status: "rascunho",
    favorita: false,
    criadoEm: "2026-04-10T11:00:00Z",
    atualizadoEm: "2026-04-10T11:45:00Z",
  },
  {
    id: "4",
    titulo: "Logística Reversa Varejo - Base",
    subtitulo: "Template oficial de Logística Reversa",
    tipo: "modelo",
    cliente: null,
    segmento: "Varejo",
    tipoServico: "Logística Reversa",
    status: "aprovada",
    favorita: true,
    criadoEm: "2026-03-15T08:00:00Z",
    atualizadoEm: "2026-03-20T10:00:00Z",
  }
];
