import { useState } from "react";
import { Download, UploadCloud, FileSpreadsheet, CheckCircle2, AlertTriangle, FileText, Play, Building, XCircle, Search, CreditCard, Clock, CheckSquare, Settings2, FileOutput } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const fmtFin = (v: number) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export default function PagamentoCNAB() {
  const [step, setStep] = useState(1);
  const [aba, setAba] = useState("gerar");

  // Dados Mockados da fila de pagamentos
  const [filaPagamentos, setFilaPagamentos] = useState([
     { id: 1, nome: "João Transportes", cpfCnpj: "000.000.000-00", banco: "Itaú (341)", conta: "00000-0", favorecido: "Próprio", chavePix: "joao@email.com", valor: 4500, osCount: 14, statusCad: "Verificado", selected: true, pendencias: [] },
     { id: 2, nome: "Auto Log Express", cpfCnpj: "11.111.111/0001-99", banco: "Bradesco (237)", conta: "1111-1", favorecido: "Próprio", chavePix: "11.111.111/0001-99", valor: 12400, osCount: 32, statusCad: "Verificado", selected: true, pendencias: [] },
     { id: 3, nome: "Roberto Silva (Agregado)", cpfCnpj: "222.222.222-22", banco: "Nubank (260)", conta: "Pendente", favorecido: "Próprio", chavePix: "-", valor: 2800, osCount: 5, statusCad: "Pendente", selected: false, pendencias: ["Falta dígito da Conta", "Sem Emissão de CIOT"] },
  ]);

  const toggleSelect = (id: number) => {
    setFilaPagamentos(prev => prev.map(p => p.id === id ? { ...p, selected: !p.selected } : p));
  };

  const prestadoresValidos = filaPagamentos.filter(p => p.pendencias.length === 0);
  const prestadoresSelecionados = filaPagamentos.filter(p => p.selected);
  const totalLote = prestadoresSelecionados.reduce((acc, curr) => acc + curr.valor, 0);

  const baixarCnab = () => {
     const fakeData = "0000000000000111111Itaú S/A... Layout FEBRABAN CNAB 240... GENERATED BY EXPRESS CONNECT HUB";
     const blob = new Blob([fakeData], { type: "text/plain" });
     const link = document.createElement("a");
     link.href = URL.createObjectURL(blob);
     link.download = `CNAB240_ITAU_341_${new Date().toISOString().slice(0,10).replace(/-/g,'')}_LOTE001.txt`;
     document.body.appendChild(link);
     link.click();
     document.body.removeChild(link);
     
     // Simulando mudança de Status pós download
     setAba("historico");
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-4">
         <div>
            <h2 className="text-xl font-bold flex items-center gap-2 text-indigo-900"><CreditCard className="w-6 h-6"/> Pagamentos em Lote (CNAB 240)</h2>
            <p className="text-sm text-muted-foreground">Orquestração bancária multi-bancos com compliance de cadastro.</p>
         </div>
         <Tabs value={aba} onValueChange={setAba} className="w-[400px]">
           <TabsList className="grid w-full grid-cols-2">
             <TabsTrigger value="gerar">Gerar Remessa</TabsTrigger>
             <TabsTrigger value="historico">Histórico & Importar Retorno</TabsTrigger>
           </TabsList>
         </Tabs>
      </div>

      {aba === "gerar" && (
         <div className="bg-white rounded-lg border shadow-sm flex flex-col min-h-[500px]">
            {/* Header Steps */}
            <div className="flex border-b divide-x">
               <div className={`p-4 flex-1 text-center font-bold ${step === 1 ? 'bg-indigo-50 text-indigo-700 border-b-2 border-b-indigo-700' : 'text-slate-400'}`}>1. Seleção Operacional</div>
               <div className={`p-4 flex-1 text-center font-bold ${step === 2 ? 'bg-indigo-50 text-indigo-700 border-b-2 border-b-indigo-700' : 'text-slate-400'}`}>2. Conferência Anti-Fraude</div>
               <div className={`p-4 flex-1 text-center font-bold ${step === 3 ? 'bg-indigo-50 text-indigo-700 border-b-2 border-b-indigo-700' : 'text-slate-400'}`}>3. Extração Febraban 240</div>
            </div>

            <div className="p-6 flex-1">
               {step === 1 && (
                 <div className="space-y-4">
                    <div className="flex gap-4">
                       <Input type="month" className="w-48" defaultValue="2026-03" />
                       <select className="flex h-10 w-48 rounded-md border text-sm px-3 bg-white"><option>Status: A Pagar</option><option>Aprovados</option></select>
                       <Button variant="outline" className="text-indigo-600 bg-indigo-50 border-indigo-200" onClick={() => {
                          setFilaPagamentos(prev => prev.map(p => ({ ...p, selected: p.pendencias.length === 0 })));
                       }}><CheckSquare className="w-4 h-4 mr-2"/> Marcar Todos Auditados</Button>
                    </div>

                    <Table>
                      <TableHeader><TableRow><TableHead className="w-12"></TableHead><TableHead>Prestador Favorecido</TableHead><TableHead>Documento / Chave Pix</TableHead><TableHead>Dados Bancários</TableHead><TableHead>Qtd. OS</TableHead><TableHead className="text-right">Valor Líquido</TableHead><TableHead></TableHead></TableRow></TableHeader>
                      <TableBody>
                         {filaPagamentos.map(p => (
                            <TableRow key={p.id} className={p.pendencias.length > 0 ? "opacity-60 bg-red-50/20" : ""}>
                               <TableCell><input type="checkbox" checked={p.selected} onChange={() => toggleSelect(p.id)} disabled={p.pendencias.length > 0} className="w-4 h-4 cursor-pointer" /></TableCell>
                               <TableCell><div className="font-bold text-slate-800">{p.nome} <Badge variant="outline" className="ml-2 text-[10px]">{p.statusCad}</Badge></div></TableCell>
                               <TableCell className="text-xs font-mono">{p.cpfCnpj} <p className="text-slate-400">Pix: {p.chavePix}</p></TableCell>
                               <TableCell className="text-xs">{p.banco} <br/> <span className="font-mono text-slate-500">C/C: {p.conta}</span></TableCell>
                               <TableCell className="font-bold text-slate-500 text-center">{p.osCount}</TableCell>
                               <TableCell className="text-right font-black text-slate-800">{fmtFin(p.valor)}</TableCell>
                               <TableCell>
                                  {p.pendencias.length > 0 && <span title="Pendências bloqueiam seleção."><AlertTriangle className="w-5 h-5 text-red-500" /></span>}
                               </TableCell>
                            </TableRow>
                         ))}
                      </TableBody>
                    </Table>
                 </div>
               )}

               {step === 2 && (
                 <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="md:col-span-2 space-y-4">
                       <h3 className="text-lg font-bold text-slate-800">Carga Aprovada para Fechamento</h3>
                       <div className="bg-slate-50 p-4 border rounded-lg max-h-[300px] overflow-auto">
                          {prestadoresSelecionados.map(p => (
                             <div key={p.id} className="flex justify-between items-center py-2 border-b last:border-0">
                                <div><p className="font-bold text-sm text-slate-800">{p.nome}</p><p className="text-xs text-muted-foreground">{p.banco} | Ag/Cc validadas</p></div>
                                <div className="text-right"><p className="font-bold text-green-700">{fmtFin(p.valor)}</p><Badge variant="outline" className="text-[10px] bg-green-50 text-green-700 mt-1"><CheckCircle2 className="w-3 h-3 mr-1"/> Seguro</Badge></div>
                             </div>
                          ))}
                       </div>
                    </div>
                    <div className="bg-red-50/50 border border-red-100 p-4 rounded-lg">
                       <h3 className="text-lg font-bold text-red-800 mb-4 flex items-center gap-2"><AlertTriangle className="w-5 h-5"/> Bloqueios Identificados</h3>
                       {filaPagamentos.filter(p => p.pendencias.length > 0).map(p => (
                          <div key={p.id} className="mb-4 bg-white p-3 border border-red-200 rounded shadow-sm">
                             <p className="font-bold text-sm text-slate-800">{p.nome}</p>
                             <ul className="mt-2 list-disc pl-4 text-xs text-red-600 font-medium space-y-1">
                                {p.pendencias.map((err, i) => <li key={i}>{err}</li>)}
                             </ul>
                             <Button size="sm" variant="outline" className="w-full mt-3 text-red-700 hover:bg-red-50 border-red-200">Corrigir Cadastro</Button>
                          </div>
                       ))}
                    </div>
                 </div>
               )}

               {step === 3 && (
                 <div className="space-y-6 max-w-3xl mx-auto py-8">
                    <div className="text-center">
                       <h3 className="text-2xl font-black text-slate-800">Exportação do TXT Bancário</h3>
                       <p className="text-muted-foreground">Você está gerando um espelho de transação Segmento A/B.</p>
                    </div>

                    <Card className="bg-indigo-50 border-indigo-200 shadow-md">
                       <CardContent className="p-6">
                          <div className="grid grid-cols-2 gap-4 mb-6">
                             <div className="space-y-1"><label className="text-xs font-bold text-slate-500 uppercase">Banco Pagador (Debitar de)</label>
                               <select className="flex h-12 w-full rounded-md border border-indigo-300 bg-white px-3 text-base font-bold text-indigo-900 shadow-sm">
                                  <option value="341">Itaú Unibanco (341) - C/C Matriz</option>
                                  <option value="237">Bradesco (237) - C/C Filial 02</option>
                                  <option value="033">Santander (033)</option>
                               </select>
                             </div>
                             <div className="space-y-1"><label className="text-xs font-bold text-slate-500 uppercase">Data Liberação TED/PIX</label>
                               <Input type="date" className="h-12 bg-white font-bold" defaultValue={new Date().toISOString().slice(0, 10)}/>
                             </div>
                          </div>
                          
                          <div className="bg-white p-4 rounded-lg border border-indigo-100 flex justify-between items-center mb-6">
                             <div><p className="text-xs font-bold text-slate-400 uppercase">Total Autorizado no Lote</p><p className="text-3xl font-black text-indigo-700">{fmtFin(totalLote)}</p></div>
                             <div className="text-right"><p className="text-xs font-bold text-slate-400 uppercase">Favorecidos Validados</p><p className="text-3xl font-black text-slate-700">{prestadoresSelecionados.length} Contas</p></div>
                          </div>

                          <div className="flex gap-4">
                             <Button onClick={baixarCnab} className="flex-1 h-14 bg-indigo-600 hover:bg-indigo-700 text-lg font-bold shadow-lg shadow-indigo-600/20"><FileText className="w-5 h-5 mr-3"/> Fazer Download CNAB 240</Button>
                             <Button variant="outline" className="flex-1 h-14 bg-white border-green-300 text-green-700 hover:bg-green-50 font-bold"><FileSpreadsheet className="w-5 h-5 mr-3"/> Relatório Excel (.xlsx)</Button>
                          </div>
                       </CardContent>
                    </Card>
                 </div>
               )}
            </div>

            {/* Footer Nav */}
            <div className="p-4 border-t flex justify-between bg-slate-50">
               <Button variant="outline" disabled={step === 1} onClick={() => setStep(s => s - 1)}>Voltar</Button>
               {step < 3 && <Button className="bg-indigo-600 hover:bg-indigo-700" onClick={() => setStep(s => s + 1)}>Avançar Etapa <Play className="w-4 h-4 ml-2"/></Button>}
            </div>
         </div>
      )}

      {aba === "historico" && (
         <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-4">
               <Card>
                  <CardHeader><CardTitle>Histórico Recente de Lotes Gerados</CardTitle></CardHeader>
                  <CardContent className="p-0">
                     <Table>
                        <TableHeader><TableRow><TableHead>Lote ID</TableHead><TableHead>Banco</TableHead><TableHead>Data Geração</TableHead><TableHead className="text-center">Qtd.</TableHead><TableHead className="text-right">Total Transacionado</TableHead><TableHead>Status Backend</TableHead></TableRow></TableHeader>
                        <TableBody>
                           <TableRow>
                              <TableCell className="font-mono text-xs font-bold text-indigo-700">LOTE-001</TableCell><TableCell className="font-bold text-sm">Itaú S.A</TableCell><TableCell className="text-xs text-slate-500">Hoje, 10:45</TableCell><TableCell className="text-center font-bold">2</TableCell><TableCell className="text-right font-black">{fmtFin(16900)}</TableCell>
                              <TableCell><Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-300"><Clock className="w-3 h-3 mr-1"/> Agd. Retorno</Badge></TableCell>
                           </TableRow>
                           <TableRow>
                              <TableCell className="font-mono text-xs font-bold text-indigo-700">LOTE-998</TableCell><TableCell className="font-bold text-sm">Bradesco</TableCell><TableCell className="text-xs text-slate-500">Ontem, 16:20</TableCell><TableCell className="text-center font-bold">18</TableCell><TableCell className="text-right font-black">{fmtFin(84200)}</TableCell>
                              <TableCell><Badge variant="outline" className="bg-green-50 text-green-700 border-green-300"><CheckCircle2 className="w-3 h-3 mr-1"/> Finalizado / Pagos</Badge></TableCell>
                           </TableRow>
                        </TableBody>
                     </Table>
                  </CardContent>
               </Card>
            </div>
            
            <div className="space-y-4">
               <Card className="border-indigo-200 shadow-lg bg-indigo-50/30">
                  <CardHeader><CardTitle className="text-indigo-900 flex items-center gap-2"><UploadCloud className="w-5 h-5"/> Importar Arquivo de Retorno</CardTitle><CardDescription>Faça upload do TXT retornado pelo Bankline (Ocorrência "00") para baixar os pagamentos reais na base.</CardDescription></CardHeader>
                  <CardContent className="space-y-4">
                     <div className="border-2 border-dashed border-indigo-200 rounded-lg p-6 flex flex-col items-center justify-center text-center bg-white hover:bg-indigo-50 transition cursor-pointer">
                        <FileOutput className="w-8 h-8 text-indigo-400 mb-2"/>
                        <p className="font-bold text-slate-700 text-sm">Solte o arquivo RETORNO.TXT aqui</p>
                        <p className="text-xs text-muted-foreground mt-1">Sincroniza automaticamente com o LOTE Original.</p>
                     </div>
                     <Button className="w-full bg-indigo-600 hover:bg-indigo-700 font-bold">Processar Conciliação de Retorno</Button>
                  </CardContent>
               </Card>
            </div>
         </div>
      )}
    </div>
  );
}
