import { Prestador } from "./types";

export const mockPrestadores: Prestador[] = [
  {
    id: "1",
    foto: "",
    nomeCompleto: "Carlos Eduardo Silva",
    nomeFantasia: "CE Transportes",
    cpfCnpj: "123.456.789-00",
    rgIe: "12.345.678-9",
    dataNascimento: "1985-03-15",
    telefone: "(11) 98765-4321",
    whatsapp: "(11) 98765-4321",
    email: "carlos@cetransportes.com.br",
    tipoParceiro: "autonomo",
    status: "ativo",
    endereco: { cep: "01310-100", rua: "Av. Paulista", numero: "1000", complemento: "Sala 501", bairro: "Bela Vista", cidade: "São Paulo", estado: "SP" },
    regiaoPrincipal: "Grande SP",
    regioesSecundarias: ["Interior SP", "Litoral SP"],
    origemCadastro: "Indicação",
    indicacao: "Magazine Luiza",
    disponibilidade: "Integral",
    turnosPreferenciais: "Manhã e Tarde",
    restricoesOperacionais: "",
    aceitaRefrigerada: false,
    aceitaUrbana: true,
    aceitaDedicada: true,
    aceitaEsporadica: true,
    contatosEmergencia: [
      { nome: "Maria Silva", telefone: "(11) 91234-5678", relacao: "Esposa" },
      { nome: "José Silva", telefone: "(11) 92345-6789", relacao: "Irmão" },
      { nome: "Ana Silva", telefone: "(11) 93456-7890", relacao: "Mãe" },
    ],
    documentos: [
      { tipo: "CNH Frente", status: "valido", dataVencimento: "2027-08-15" },
      { tipo: "CNH Verso", status: "valido", dataVencimento: "2027-08-15" },
      { tipo: "Documento Pessoal", status: "valido" },
      { tipo: "Comprovante de Residência", status: "valido" },
      { tipo: "Comprovante Bancário", status: "valido" },
      { tipo: "Contrato", status: "valido", dataVencimento: "2026-12-31" },
      { tipo: "CRLV", status: "vencendo", dataVencimento: "2026-03-30" },
      { tipo: "ANTT", status: "valido", dataVencimento: "2026-11-15" },
      { tipo: "Apólice de Seguro", status: "valido", dataVencimento: "2026-09-01" },
    ],
    veiculos: [
      {
        id: "v1", tipoVeiculo: "van", subcategoria: "urbano", tipoCarroceria: "bau",
        classificacaoTermica: "seco", placa: "ABC-1D23", renavam: "12345678901",
        marca: "Mercedes-Benz", modelo: "Sprinter 415", ano: 2022, cor: "Branco",
        capacidadeKg: 1500, capacidadeM3: 12, comprimento: 3.2, largura: 1.8, altura: 1.9,
        qtdPallets: 4, proprietario: "Carlos Eduardo Silva", rastreador: "Sascar",
        seguradora: "Porto Seguro", validadeDocumental: "2026-12-15", status: "ativo",
      },
    ],
    banco: "Itaú", agencia: "1234", conta: "56789", digito: "0", tipoConta: "Corrente",
    favorecido: "Carlos Eduardo Silva", cpfCnpjFavorecido: "123.456.789-00",
    chavePix: "carlos@cetransportes.com.br", tipoChavePix: "E-mail",
    valorDiaria: 350, valorKm: 2.8, valorSaida: 180, fixoMensal: 0,
    valorAjudante: 120, valorEspera: 45, valorReentrega: 95, valorDevolucao: 85,
    periodicidadePagamento: "Quinzenal", prazoPagamento: "15 dias",
    formaPreferencialPagamento: "Transferência", contaContabil: "3.1.01", centroCusto: "OPS-SP",
    retencoes: "", conferenciManual: false, observacoesFinanceiras: "",
    scoreInterno: 4.5, avaliacaoOperacional: "Excelente pontualidade e cuidado com a carga.",
    qtdOperacoes: 342, indiceAceite: 96, indiceComparecimento: 98, indiceEntregaNoPrazo: 94,
    historicoOcorrencias: [
      { data: "2026-02-10", descricao: "Atraso de 30min na coleta — trânsito na Marginal" },
      { data: "2025-11-05", descricao: "Avaria leve em embalagem — ressarcido" },
    ],
    historicoBloqueios: [
      { data: "2025-06-01", motivo: "CNH vencida", tipo: "Bloqueio" },
      { data: "2025-06-10", motivo: "CNH renovada", tipo: "Reativação" },
    ],
    dataCadastro: "2023-04-15",
    dataAprovacao: "2023-04-20",
    historicoAlteracoes: [
      { campo: "WhatsApp", antes: "(11) 91111-2222", depois: "(11) 98765-4321", usuario: "admin@conexaoexpress.com.br", data: "2026-01-15" },
      { campo: "Região secundária", antes: "—", depois: "Litoral SP", usuario: "admin@conexaoexpress.com.br", data: "2025-10-02" },
    ],
    ultimaAtualizacao: "2026-03-20",
    ultimoUsuario: "admin@conexaoexpress.com.br",
    observacoesTorre: "Parceiro confiável para rotas SP capital. Priorizar em operações urgentes.",
  },
  {
    id: "2", foto: "", nomeCompleto: "TransLog Parceiros LTDA", nomeFantasia: "TransLog SP",
    cpfCnpj: "12.345.678/0001-90", telefone: "(11) 3456-7890", whatsapp: "(11) 94567-8901",
    email: "contato@translogsp.com.br", tipoParceiro: "agregado", status: "ativo",
    endereco: { cep: "09110-000", rua: "Rua Industrial", numero: "500", bairro: "Centro", cidade: "Santo André", estado: "SP" },
    regiaoPrincipal: "ABC Paulista", aceitaRefrigerada: true, aceitaUrbana: true, aceitaDedicada: false, aceitaEsporadica: true,
    contatosEmergencia: [
      { nome: "Roberto Alves", telefone: "(11) 95678-1234", relacao: "Sócio" },
      { nome: "Fernanda Costa", telefone: "(11) 96789-2345", relacao: "Gerente" },
      { nome: "Paulo Mendes", telefone: "(11) 97890-3456", relacao: "Supervisor" },
    ],
    documentos: [
      { tipo: "CNH Frente", status: "valido", dataVencimento: "2028-02-20" },
      { tipo: "Contrato Social", status: "valido" },
      { tipo: "CRLV", status: "valido", dataVencimento: "2026-12-01" },
    ],
    veiculos: [
      { id: "v2", tipoVeiculo: "truck", subcategoria: "pesado", tipoCarroceria: "bau_refrigerado", classificacaoTermica: "refrigerado", placa: "DEF-5G67", renavam: "98765432101", marca: "Volvo", modelo: "VM 270", ano: 2023, cor: "Azul", capacidadeKg: 12000, capacidadeM3: 45, qtdPallets: 16, proprietario: "TransLog Parceiros LTDA", rastreador: "Autotrac", seguradora: "Allianz", status: "ativo" },
      { id: "v3", tipoVeiculo: "toco", subcategoria: "medio", tipoCarroceria: "sider", classificacaoTermica: "seco", placa: "GHI-8J90", renavam: "11223344556", marca: "Mercedes-Benz", modelo: "Atego 1719", ano: 2021, cor: "Branco", capacidadeKg: 8000, capacidadeM3: 35, qtdPallets: 12, proprietario: "TransLog Parceiros LTDA", status: "ativo" },
    ],
    banco: "Bradesco", agencia: "4567", conta: "12345", digito: "6", tipoConta: "Corrente",
    favorecido: "TransLog Parceiros LTDA", cpfCnpjFavorecido: "12.345.678/0001-90",
    chavePix: "12345678000190", tipoChavePix: "CNPJ",
    valorDiaria: 650, valorKm: 4.5, valorSaida: 320,
    periodicidadePagamento: "Semanal", prazoPagamento: "7 dias",
    formaPreferencialPagamento: "Boleto", conferenciManual: true,
    scoreInterno: 4.2, qtdOperacoes: 580, indiceAceite: 88, indiceComparecimento: 95, indiceEntregaNoPrazo: 91,
    historicoOcorrencias: [],
    historicoBloqueios: [],
    dataCadastro: "2022-08-10", dataAprovacao: "2022-08-15",
    historicoAlteracoes: [], ultimaAtualizacao: "2026-03-18", ultimoUsuario: "operador@conexaoexpress.com.br",
  },
  {
    id: "3", foto: "", nomeCompleto: "João Pedro Oliveira", cpfCnpj: "987.654.321-00",
    telefone: "(21) 99876-5432", email: "joao.oliveira@email.com", tipoParceiro: "esporadico", status: "analise",
    endereco: { cep: "20040-020", rua: "Rua da Assembleia", numero: "45", bairro: "Centro", cidade: "Rio de Janeiro", estado: "RJ" },
    regiaoPrincipal: "Rio de Janeiro", aceitaRefrigerada: false, aceitaUrbana: true, aceitaDedicada: false, aceitaEsporadica: true,
    contatosEmergencia: [
      { nome: "Lucia Oliveira", telefone: "(21) 98765-1111", relacao: "Mãe" },
      { nome: "Pedro Oliveira", telefone: "(21) 98765-2222", relacao: "Pai" },
      { nome: "Ana Oliveira", telefone: "(21) 98765-3333", relacao: "Irmã" },
    ],
    documentos: [
      { tipo: "CNH Frente", status: "pendente" },
      { tipo: "Comprovante de Residência", status: "valido" },
    ],
    veiculos: [
      { id: "v4", tipoVeiculo: "utilitario_leve", subcategoria: "leve", tipoCarroceria: "furgao", classificacaoTermica: "seco", placa: "KLM-2N34", renavam: "55667788990", marca: "Fiat", modelo: "Fiorino", ano: 2020, cor: "Branco", capacidadeKg: 650, capacidadeM3: 4, proprietario: "João Pedro Oliveira", status: "ativo" },
    ],
    conferenciManual: false, scoreInterno: 3.0, qtdOperacoes: 12, indiceAceite: 75, indiceComparecimento: 83, indiceEntregaNoPrazo: 80,
    historicoOcorrencias: [], historicoBloqueios: [],
    dataCadastro: "2026-03-01", historicoAlteracoes: [], ultimaAtualizacao: "2026-03-01", ultimoUsuario: "admin@conexaoexpress.com.br",
  },
  {
    id: "4", foto: "", nomeCompleto: "Expresso Sul Logística EIRELI", nomeFantasia: "Sul Express",
    cpfCnpj: "45.678.901/0001-23", telefone: "(41) 3321-5678", email: "contato@sulexpress.com.br",
    tipoParceiro: "fixo", status: "ativo",
    endereco: { cep: "80010-000", rua: "Rua XV de Novembro", numero: "200", bairro: "Centro", cidade: "Curitiba", estado: "PR" },
    regiaoPrincipal: "Paraná", regioesSecundarias: ["Santa Catarina"],
    aceitaRefrigerada: true, aceitaUrbana: true, aceitaDedicada: true, aceitaEsporadica: false,
    contatosEmergencia: [
      { nome: "Marcos Souza", telefone: "(41) 99876-1234", relacao: "Gerente Operacional" },
      { nome: "Clara Lima", telefone: "(41) 99876-5678", relacao: "RH" },
      { nome: "Diego Santos", telefone: "(41) 99876-9012", relacao: "Diretor" },
    ],
    documentos: [
      { tipo: "CNH Frente", status: "valido", dataVencimento: "2027-05-10" },
      { tipo: "Contrato Social", status: "valido" },
      { tipo: "ANTT", status: "vencido", dataVencimento: "2026-02-28" },
    ],
    veiculos: [
      { id: "v5", tipoVeiculo: "carreta", subcategoria: "pesado", tipoCarroceria: "bau_refrigerado", classificacaoTermica: "refrigerado", placa: "OPQ-5R67", renavam: "99887766554", marca: "Scania", modelo: "R450", ano: 2023, cor: "Prata", capacidadeKg: 28000, capacidadeM3: 85, qtdPallets: 30, proprietario: "Expresso Sul Logística EIRELI", rastreador: "Omnilink", seguradora: "Tokio Marine", status: "ativo" },
    ],
    banco: "Banco do Brasil", agencia: "7890", conta: "67890", digito: "1", tipoConta: "Corrente",
    valorDiaria: 1200, valorKm: 6.5, fixoMensal: 18000,
    periodicidadePagamento: "Mensal", prazoPagamento: "30 dias",
    conferenciManual: false, scoreInterno: 4.8, qtdOperacoes: 920,
    indiceAceite: 99, indiceComparecimento: 99, indiceEntregaNoPrazo: 97,
    historicoOcorrencias: [], historicoBloqueios: [],
    dataCadastro: "2021-02-10", dataAprovacao: "2021-02-15",
    historicoAlteracoes: [], ultimaAtualizacao: "2026-03-22", ultimoUsuario: "admin@conexaoexpress.com.br",
  },
  {
    id: "5", foto: "", nomeCompleto: "Ricardo Mendes", cpfCnpj: "456.789.012-34",
    telefone: "(31) 98765-0000", email: "ricardo.mendes@email.com",
    tipoParceiro: "terceiro", status: "bloqueado",
    endereco: { cep: "30130-000", rua: "Av. Afonso Pena", numero: "1500", bairro: "Centro", cidade: "Belo Horizonte", estado: "MG" },
    regiaoPrincipal: "Belo Horizonte", aceitaRefrigerada: false, aceitaUrbana: true, aceitaDedicada: false, aceitaEsporadica: true,
    contatosEmergencia: [
      { nome: "Patrícia Mendes", telefone: "(31) 99111-2222", relacao: "Esposa" },
      { nome: "Luís Mendes", telefone: "(31) 99333-4444", relacao: "Pai" },
      { nome: "Carla Mendes", telefone: "(31) 99555-6666", relacao: "Irmã" },
    ],
    documentos: [
      { tipo: "CNH Frente", status: "vencido", dataVencimento: "2025-12-01" },
      { tipo: "CRLV", status: "vencido", dataVencimento: "2025-11-30" },
    ],
    veiculos: [
      { id: "v6", tipoVeiculo: "hr", subcategoria: "leve", tipoCarroceria: "bau", classificacaoTermica: "seco", placa: "STU-8V90", renavam: "33445566778", marca: "Hyundai", modelo: "HR", ano: 2019, cor: "Branco", capacidadeKg: 1300, capacidadeM3: 8, proprietario: "Ricardo Mendes", status: "inativo" },
    ],
    conferenciManual: true, scoreInterno: 2.1, qtdOperacoes: 45,
    indiceAceite: 60, indiceComparecimento: 70, indiceEntregaNoPrazo: 65,
    historicoOcorrencias: [
      { data: "2025-11-20", descricao: "Não compareceu na coleta sem aviso prévio" },
      { data: "2025-10-05", descricao: "Carga entregue com avaria significativa" },
    ],
    historicoBloqueios: [
      { data: "2025-12-01", motivo: "CNH e CRLV vencidos + ocorrências reiteradas", tipo: "Bloqueio" },
    ],
    dataCadastro: "2024-06-01", dataAprovacao: "2024-06-05",
    historicoAlteracoes: [
      { campo: "Status", antes: "Ativo", depois: "Bloqueado", usuario: "admin@conexaoexpress.com.br", data: "2025-12-01" },
    ],
    ultimaAtualizacao: "2025-12-01", ultimoUsuario: "admin@conexaoexpress.com.br",
    observacoesTorre: "Bloqueado por documentação vencida e histórico de ocorrências. Reavaliar após regularização.",
  },
  {
    id: "6", foto: "", nomeCompleto: "Logística Rápida ME", nomeFantasia: "RápidoFrete",
    cpfCnpj: "67.890.123/0001-45", telefone: "(11) 2345-6789", email: "ops@rapidofrete.com.br",
    tipoParceiro: "agregado", status: "ativo",
    endereco: { cep: "06454-000", rua: "Rua Castelo Branco", numero: "88", bairro: "Alphaville", cidade: "Barueri", estado: "SP" },
    regiaoPrincipal: "Grande SP", aceitaRefrigerada: false, aceitaUrbana: true, aceitaDedicada: true, aceitaEsporadica: false,
    contatosEmergencia: [
      { nome: "Sandra Reis", telefone: "(11) 95555-1111", relacao: "Sócia" },
      { nome: "Bruno Alves", telefone: "(11) 95555-2222", relacao: "Motorista líder" },
      { nome: "Camila Souza", telefone: "(11) 95555-3333", relacao: "Administrativa" },
    ],
    documentos: [
      { tipo: "CNH Frente", status: "valido", dataVencimento: "2027-10-10" },
      { tipo: "Contrato", status: "valido", dataVencimento: "2026-12-31" },
      { tipo: "CRLV", status: "valido", dataVencimento: "2026-08-15" },
    ],
    veiculos: [
      { id: "v7", tipoVeiculo: "van", subcategoria: "urbano", tipoCarroceria: "bau", classificacaoTermica: "seco", placa: "WXY-1Z23", renavam: "44556677889", marca: "Renault", modelo: "Master", ano: 2023, cor: "Branco", capacidadeKg: 1800, capacidadeM3: 14, qtdPallets: 5, proprietario: "Logística Rápida ME", rastreador: "Sascar", status: "ativo" },
    ],
    banco: "Santander", agencia: "3456", conta: "78901", digito: "2", tipoConta: "Corrente",
    valorDiaria: 400, valorKm: 3.2, valorSaida: 200,
    periodicidadePagamento: "Semanal", prazoPagamento: "7 dias",
    conferenciManual: false, scoreInterno: 4.0, qtdOperacoes: 215,
    indiceAceite: 92, indiceComparecimento: 96, indiceEntregaNoPrazo: 90,
    historicoOcorrencias: [], historicoBloqueios: [],
    dataCadastro: "2023-11-01", dataAprovacao: "2023-11-05",
    historicoAlteracoes: [], ultimaAtualizacao: "2026-03-19", ultimoUsuario: "operador@conexaoexpress.com.br",
  },
];
